# Generated by Django 4.0.2 on 2022-02-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('inprogess', 'In Progess'), ('new', 'New'), ('won', 'Won'), ('contacted', 'Contacted'), ('lost', 'Lost')], default='new', max_length=25),
        ),
    ]
